[package]
name = "playdate-controls"
version = "0.1.1"
edition = "2021"

readme = "README.md"
license = "MIT OR Apache-2.0"
authors = ["Alex Koz <a@koz.email>"]
description = "High-level controls API built on-top of Playdate API"
homepage = "https://github.com/boozook/playdate"
repository = "https://github.com/boozook/playdate.git"


[features]
default = ["sys/default"]
lang-items = ["sys/lang-items"]
allocator = ["sys/allocator"]
panic-handler = ["sys/panic-handler"]
eh-personality = ["sys/eh-personality"]
entry-point = ["sys/entry-point"]
error-ctx = ["sys/error-ctx"]
bindgen-runtime = ["sys/bindgen-runtime"]
bindgen-static = ["sys/bindgen-static"]
bindings-derive-default = ["sys/bindings-derive-default"]
bindings-derive-eq = ["sys/bindings-derive-eq"]
bindings-derive-copy = ["sys/bindings-derive-copy"]
bindings-derive-debug = ["sys/bindings-derive-debug"]
bindings-derive-hash = ["sys/bindings-derive-hash"]
bindings-derive-ord = ["sys/bindings-derive-ord"]
bindings-derive-partialeq = ["sys/bindings-derive-partialeq"]
bindings-derive-partialord = ["sys/bindings-derive-partialord"]
bindings-derive-constparamty = ["sys/bindings-derive-constparamty"]
bindings-documentation = ["sys/bindings-documentation"]


[dependencies.sys]
path = "../sys"
version = "0.1"
package = "playdate-sys"
default-features = false


[[example]]
name = "buttons"
crate-type = ["dylib", "staticlib"]
path = "examples/buttons.rs"

[[example]]
name = "accelerometer"
crate-type = ["dylib", "staticlib"]
path = "examples/accelerometer.rs"

[package.metadata.playdate]
bundle-id = "rs.playdate.ctrl"
