api:
  - any:
      - "api/**"
      - "components/**"

pre-built bindings:
  - any:
      - "api/gen/*"

cargo:
  - any:
      - "cargo/**"

bindgen:
  - any:
      - "support/bindgen/**"

docs:
  - any:
      - "**/*.md"
      - "**/*.txt"
