api:
  - changed-files:
      - any-glob-to-any-file:
          - "api/**"
          - "components/**"
pre-built bindings:
  - any:
      - changed-files:
          - any-glob-to-any-file: "api/gen/*"
      - head-branch: api/sys/pre-build/.*

cargo:
  - changed-files:
      - any-glob-to-any-file: "cargo/**"

bindgen:
  - changed-files:
      - any-glob-to-any-file:
          - "support/bindgen/**"
          - "support/bindgen-cfg/**"
docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "**/*.txt"
