[package]
name = "playdate-sound"
version = "0.1.0"
edition = "2021"

readme = "README.md"
authors = ["Alex Koz <a@koz.email>"]
description = "High-level sound API built on-top of Playdate API"
homepage = "https://github.com/boozook/playdate"
repository = "https://github.com/boozook/playdate.git"


[features]
default = ["sys/default"]
# sys- features:
lang-items = ["sys/lang-items"]
allocator = ["sys/allocator"]
panic-handler = ["sys/panic-handler"]
eh-personality = ["sys/eh-personality"]
error-ctx = ["sys/error-ctx"]
bindgen-runtime = ["sys/bindgen-runtime"]
bindings-pre-built = ["sys/bindings-pre-built"]
bindings-generate = ["sys/bindings-generate"]
bindings-derive-default = ["sys/bindings-derive-default"]
bindings-derive-eq = ["sys/bindings-derive-eq"]
bindings-derive-copy = ["sys/bindings-derive-copy"]
bindings-derive-debug = ["sys/bindings-derive-debug"]
bindings-derive-hash = ["sys/bindings-derive-hash"]
bindings-derive-ord = ["sys/bindings-derive-ord"]
bindings-derive-partialeq = ["sys/bindings-derive-partialeq"]
bindings-derive-partialord = ["sys/bindings-derive-partialord"]
bindings-derive-constparamty = ["sys/bindings-derive-constparamty"]
bindings-documentation = ["sys/bindings-documentation"]


[dependencies.sys]
path = "../sys"
package = "playdate-sys"
default-features = false

[dependencies.fs]
path = "../fs"
package = "playdate-fs"
default-features = false


[[example]]
name = "sp-simple"
crate-type = ["dylib", "staticlib"]
path = "examples/sp-simple.rs"

# [[example]]
# name = "sp-cached"
# crate-type = ["dylib", "staticlib"]
# path = "examples/sp-cached.rs"
# required-features = ["bindings-derive-cache"]

[[example]]
name = "fp-simple"
crate-type = ["dylib", "staticlib"]
path = "examples/fp-simple.rs"


[package.metadata.playdate]
bundle-id = "rs.playdate.sound"

# XXX: really important feature:
# TODO: impl assets for cargo-targets (examples, etc...)
# this should be "dev-assets" in nearest future release
[package.metadata.playdate.assets]
"sfx/" = "${PLAYDATE_SDK_PATH}/Examples/Level 1-1/Source/sfx/main_theme.wav"
