[package]
name = "playdate-build-utils"
version = "0.1.0"
edition = "2021"

readme = "README.md"
license = "MIT OR Apache-2.0"
authors = ["Alex Koz <a@koz.email>"]
description = "Utils that help to build program with Rust and Playdate API"
keywords = ["playdate", "utility"]
categories = ["development-tools::build-utils"]
homepage = "https://github.com/boozook/playdate"
repository = "https://github.com/boozook/playdate.git"
documentation = "https://docs.rs/playdate-build-utils"


[dependencies]
dirs = "5.0"
log = { version = "0.4", optional = true }


[features]
default = ["log", "cargo-message"]
cargo-message = []                 # cargo notifications & warnings and logging
