name: Auto-merge
on:
  pull_request:
    types: ready_for_review
  pull_request_target:
    types: ready_for_review

permissions:
  contents: write
  pull-requests: write

jobs:
  approve:
    continue-on-error: true
    runs-on: ubuntu-latest
    if: ${{ github.actor == github.repository_owner }}
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Approve
        # if there is no requested reviewers specified:
        if: !github.event.pull_request.requested_reviewers
        run: gh pr review --approve "${{github.event.pull_request.html_url}}"

      - name: Auto-merge
        run: gh pr merge --auto --rebase "${{github.event.pull_request.html_url}}"


