name: "Labels"
on:
  pull_request_target:

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v4
        with:
          dot: false
          sync-labels: false
