name: Post
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      message:
        description: "Just message to post."
        required: false
  workflow_call:
    inputs:
      message:
        type: string
        description: "Just message to post."
        required: false

jobs:
  post:
    name: Post
    runs-on: ubuntu-latest
    steps:
      - name: Repo Url
        id: url
        run: |
          URL="${{ github.event_name == 'release' && github.event.release.html_url || format('{0}/{1}', github.server_url, github.repository) }}"
          echo "value=$URL" >> "$GITHUB_OUTPUT"

      - name: Prepare Words
        id: words
        env:
          XRELEASE: ${{ github.event_name == 'release' && (github.event.release.prerelease && 'pre-release' || 'release') || '' }}
        run: echo "release=$XRELEASE" >> "$GITHUB_OUTPUT"

      - name: Toot
        id: mastodon
        uses: cbrgm/mastodon-github-action@v2.0.4
        with:
          message: |
            🦀 Rusty Playdate Updated!

            ${{ inputs.message || (github.event_name == 'release' && format('New {0} published: {1}', steps.words.outputs.release, github.event.release.name) || '') }}

            ${{ steps.url.outputs.value }}

            #RustLang #playdate

          # TODO: Write good-look link like [github.event.repository.name](url)

          language: "en"
          visibility: public # use `unlisted` for tests
          url: ${{ secrets.MASTODON_URL }}
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
