name: Triage
on:
  pull_request_target:
  workflow_dispatch:
    inputs:
      pr:
        description: The pull request number(s).
        type: string
        required: false

jobs:
  labels:
    name: Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5.0.0
        with:
          sync-labels: true
          pr-number: ${{ github.event.inputs.pr || '' }}
